In [1]:
import numpy as np
import pandas as pd
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import tushare as ts

In [2]:
import defLevel as dlv
import isolation as iso

In [3]:
symbol = '600438'
df = ts.get_k_data(symbol,start='2017-01-01')
df.columns = ['Tm','O','C','H','L','V','code']
dtCnt = len(df)

In [4]:
df

             Tm       O       C       H       L         V    code
0    2017-01-03   6.276   6.364   6.374   6.246  140726.0  600438
1    2017-01-04   6.305   6.374   6.384   6.305  108487.0  600438
2    2017-01-05   6.374   6.295   6.374   6.276  110492.0  600438
3    2017-01-06   6.295   6.295   6.355   6.266   77574.0  600438
4    2017-01-09   6.295   6.256   6.335   6.177   93708.0  600438
5    2017-01-10   6.217   6.167   6.246   6.158  114766.0  600438
6    2017-01-11   6.158   6.118   6.207   6.108   70877.0  600438
7    2017-01-12   6.128   6.118   6.167   6.089   57142.0  600438
8    2017-01-13   6.167   6.118   6.167   5.892  208629.0  600438
9    2017-01-16   6.089   6.207   6.246   5.911  322505.0  600438
10   2017-01-17   6.118   6.207   6.236   6.089   58487.0  600438
11   2017-01-18   6.227   6.108   6.227   6.089   55206.0  600438
12   2017-01-19   6.108   6.029   6.108   6.000   53740.0  600438
13   2017-01-20   6.039   6.098   6.118   5.990  103720.0  600438
14   2017-01-23   6.187   6.158   6.227   6.118   56145.0  600438
15   2017-01-24   6.158   6.089   6.177   6.069   58217.0  600438
16   2017-01-25   6.069   6.098   6.128   6.049   27080.0  600438
17   2017-01-26   6.098   6.138   6.148   6.098   32418.0  600438
18   2017-02-03   6.138   6.069   6.158   6.059   43256.0  600438
19   2017-02-06   6.098   6.118   6.138   6.069   70211.0  600438
20   2017-02-07   6.118   6.069   6.118   6.039   58430.0  600438
21   2017-02-08   6.079   6.098   6.098   6.010   76897.0  600438
22   2017-02-09   6.108   6.118   6.128   6.069   78640.0  600438
23   2017-02-10   6.128   6.138   6.148   6.098   83373.0  600438
24   2017-02-13   6.138   6.148   6.158   6.108   92747.0  600438
25   2017-02-14   6.138   6.089   6.138   6.059   80999.0  600438
26   2017-02-15   6.089   6.039   6.098   6.010   84835.0  600438
27   2017-02-16   6.029   6.039   6.059   6.010   60923.0  600438
28   2017-02-17   6.020   5.961   6.039   5.951  103974.0  600438
29   2017-02-20   5.961   6.000   6.029   5.951   71952.0  600438
..          ...     ...     ...     ...     ...       ...     ...
188  2017-10-13   9.790   9.790  10.130   9.690  264737.0  600438
189  2017-10-16   9.790   9.330   9.850   9.310  440423.0  600438
190  2017-10-17   9.330   9.390   9.550   9.040  289309.0  600438
191  2017-10-18   9.380   9.180   9.460   9.140  207132.0  600438
192  2017-10-19   9.190   9.300   9.360   9.070  266025.0  600438
193  2017-10-20   9.280   9.600   9.750   9.180  320826.0  600438
194  2017-10-23   9.770   9.680   9.890   9.450  288329.0  600438
195  2017-10-24   9.700   9.910   9.980   9.530  315788.0  600438
196  2017-10-25   9.880   9.910  10.160   9.850  188377.0  600438
197  2017-10-26   9.900  10.200  10.400   9.800  500385.0  600438
198  2017-10-27  10.150  10.070  10.290   9.950  265873.0  600438
199  2017-10-30  10.090   9.630  10.120   9.510  420650.0  600438
200  2017-10-31   9.640   9.840   9.850   9.510  240083.0  600438
201  2017-11-01   9.800  10.110  10.210   9.720  382925.0  600438
202  2017-11-02  10.010  10.020  10.180   9.930  196170.0  600438
203  2017-11-03  10.000   9.530  10.060   9.390  398226.0  600438
204  2017-11-06   9.430  10.130  10.150   9.410  552641.0  600438
205  2017-11-07  10.530  10.520  10.810  10.310  714135.0  600438
206  2017-11-08  10.570  11.180  11.380  10.570  687631.0  600438
207  2017-11-09  11.020  11.290  11.630  10.990  564997.0  600438
208  2017-11-10  11.480  12.420  12.420  11.320  849071.0  600438
209  2017-11-13  12.670  13.290  13.660  12.640  878515.0  600438
210  2017-11-14  13.120  12.680  13.660  12.540  836450.0  600438
211  2017-11-15  12.830  12.480  12.880  12.040  682470.0  600438
212  2017-11-16  12.730  13.390  13.520  12.500  648552.0  600438
213  2017-11-17  13.310  13.030  14.420  12.800  738936.0  600438
214  2017-11-20  13.100  13.970  14.200  12.800  631119.0  600438
215  2017-11-21  13.960  14.210  14.680  13.800  662230.0  600438
216  2017-11-22  14.260  13.670  14.260  13.050  681053.0  600438
217  2017-11-23  13.500  12.300  13.500  12.300  577337.0  600438

[218 rows x 7 columns]

In [5]:
stdA = [[df.O[0],df.H[0],df.L[0],df.C[0],df.Tm[0]]]
drt_std = 0

Lv1A = [[df.Tm[0],df.O[0], 0]]
cnt_up_Lv1 = 2
cnt_dn_Lv1 = 2

In [6]:
mark = []

In [7]:
for i in range(1,dtCnt):
    #print '============================='    
  
    currentK = [df.O[i],df.H[i],df.L[i],df.C[i],df.Tm[i]]
    Fstd = 0
    FLv1 = 0
    FLv2 = 0
    stdA,drt_std,Fstd = dlv.std(currentK,stdA,drt_std)
    istd = len(stdA) -1

    
    if istd > 3 and Fstd == 1:
        Lv1A,FLv1,cnt_up_Lv1,cnt_dn_Lv1 = dlv.Lv1(stdA,Lv1A,cnt_up_Lv1,cnt_dn_Lv1)
    iLv1 = len(Lv1A) - 1
    if (FLv1 == 1 or FLv1 == -1) and iLv1 > 2:
        mark.append([i,Lv1A[iLv1][1],'lv1'])  
        rp1,rp2 = dlv.get_rp(Lv1A,iLv1-3)
        txt = '{:.2}'.format(rp1) +','+ '{:.2}'.format(rp2)
        mark.append([i,Lv1A[iLv1][1]+1,txt])
    
    if iLv1 == 3 and FLv1 == 1 and Fstd == 1:
        
        if Lv1A[2][2] == 1: 
            std_btm =[[Lv1A[0][1],Lv1A[1][1],Lv1A[0][0],0]]
            std_tp =[[Lv1A[2][1],Lv1A[1][1],Lv1A[1][0],0]]            
            
        elif Lv1A[2][2] == -1:
            std_tp =[[Lv1A[1][1],Lv1A[0][1],Lv1A[0][0],0]]
            std_btm =[[Lv1A[1][1],Lv1A[2][1],Lv1A[1][0],0]]
        drt_st = 0
        drt_sb = 0

In [8]:
Lv1A

[[u'2017-01-03', 6.2759999999999998, 0],
 [u'2017-01-13', 5.8920000000000003, 1],
 [u'2017-01-23', 6.2270000000000003, -1],
 [u'2017-02-08', 6.0099999999999998, 1],
 [u'2017-02-13', 6.1580000000000004, -1],
 [u'2017-02-17', 5.9509999999999996, 1],
 [u'2017-02-27', 6.2069999999999999, -1],
 [u'2017-03-03', 5.9900000000000002, 1],
 [u'2017-03-13', 6.6900000000000004, -1],
 [u'2017-03-30', 6.0789999999999997, 1],
 [u'2017-04-13', 6.5220000000000002, -1],
 [u'2017-06-02', 5.0739999999999998, 1],
 [u'2017-07-04', 6.1200000000000001, -1],
 [u'2017-07-18', 5.6799999999999997, 1],
 [u'2017-08-08', 7.6799999999999997, -1],
 [u'2017-08-18', 6.5899999999999999, 1],
 [u'2017-09-19', 10.23, -1],
 [u'2017-09-26', 8.7200000000000006, 1],
 [u'2017-10-11', 10.65, -1],
 [u'2017-10-17', 9.0399999999999991, 1],
 [u'2017-10-26', 10.4, -1],
 [u'2017-11-03', 9.3900000000000006, 1],
 [u'2017-11-21', 14.68, -1]]

In [9]:
T_count_list = []
for i in range(len(Lv1A)):
    if i < len(Lv1A) - 1:
        t = iso.T_count(Lv1A[i][0],Lv1A[i+1][0],df)
        T_count_list.append(t)
    else:
        T_count_list.append(0)
T_count_list

[8, 6, 7, 3, 4, 6, 4, 6, 13, 8, 33, 22, 10, 15, 8, 22, 5, 6, 4, 7, 6, 12, 0]

In [10]:
change_list = []
for i in range(len(Lv1A)):
    if i < len(Lv1A) - 1:
        t = abs(Lv1A[i+1][1] - Lv1A[i][1])
        change_list.append(t)
    else:
        change_list.append(0)
change_list

[0.38399999999999945,
 0.33499999999999996,
 0.21700000000000053,
 0.14800000000000058,
 0.20700000000000074,
 0.25600000000000023,
 0.21699999999999964,
 0.70000000000000018,
 0.61100000000000065,
 0.4430000000000005,
 1.4480000000000004,
 1.0460000000000003,
 0.44000000000000039,
 2.0,
 1.0899999999999999,
 3.6400000000000006,
 1.5099999999999998,
 1.9299999999999997,
 1.6100000000000012,
 1.3600000000000012,
 1.0099999999999998,
 5.2899999999999991,
 0]

In [11]:
k_list = []
for i in range(len(T_count_list)-1):
    tmp = change_list[i] / T_count_list[i]
    k_list.append(tmp)
k_list

[0.047999999999999932,
 0.055833333333333325,
 0.031000000000000076,
 0.049333333333333527,
 0.051750000000000185,
 0.042666666666666707,
 0.054249999999999909,
 0.1166666666666667,
 0.047000000000000049,
 0.055375000000000063,
 0.043878787878787892,
 0.047545454545454557,
 0.044000000000000039,
 0.13333333333333333,
 0.13624999999999998,
 0.16545454545454549,
 0.30199999999999994,
 0.3216666666666666,
 0.4025000000000003,
 0.19428571428571445,
 0.16833333333333331,
 0.44083333333333324]

In [145]:
# 2nd k, HL initiation=====================================================
# columns = ['id','Tm','L','H','scale','count','sd']
Distri_list =[[]]
sd = 20 # scale_density


L = min(df.L[0],df.L[1])
H = max(df.H[0],df.H[1])
internal = ( H -L ) / sd
scale_list = np.arange(L,H,internal)
count_list = np.zeros(sd)

cur_distri = {
    'id':0,
    'Tm':df.Tm[0],
    'L':min(df.L[0],df.L[1]),
    'H':max(df.H[0],df.H[1]),
    'scale':scale_list,
    'count':count_list,
    'sd':sd
}

Distri_list[0] = cur_distri

In [146]:
cur_distri['H']

6.3840000000000003

In [147]:
# every new k:
#     update HL, update scale[] & internal, 
#     tm_unit = k_H - k_L / internal
#     update distrabution: slice scale[], count[] = tm_unit
#     distribution list columns = ['id 0','Tm 1','L 2','H 3','scale','count']
#     cur_distri = [0,HL_Tm,L,H,scale_list,count_list]
i = 3
tm_unit_value = 1
tm_unit = 'd'
#HL_id = cur_HL[0]

L = min(cur_distri['L'] ,df.L[i])
H = max(cur_distri['H'] ,df.H[i])
if L != cur_distri['L'] or H != cur_distri['H']:  # if HL changed: update scale
    internal = ( H - L ) / sd
    scale_list = np.arange(L,H,internal)
    print 'scale list change:',df.Tm[i]
    
# count_unit = tm_unit_value /float(int(( df.H[i] - df.L[i] ) / internal)+ 2)
count_times = 0.0
for scale in scale_list:
    if df.L[i] <= scale and scale <= df.H[i]:
        count_times += 1
count_unit = tm_unit_value / count_times

for j,scale in enumerate(scale_list):
    print j,scale,count_list[j],':',
    if df.L[i] <= scale and scale <= df.H[i]:
        count_list[j] += count_unit
        print 'count:' + str(count_list[j])
    else:
        print 'count:' + str(count_list[j])

count_list         

print H,L,internal,df.H[i] - df.L[i],df.H[i] , df.L[i],tm_unit,count_unit

In [148]:
# distribute one k to scale
def distri_k_to_scale(kDf, scaleL, countL):
    count_times = 0.0
    for scale in scaleL:
        if kDf.L <= scale and scale <= kDf.H:
            count_times += 1
    count_unit = tm_unit_value / count_times

    for j,scale in enumerate(scaleL):
        print j,scale,countL[j],':',
        if kDf.L <= scale and scale <= kDf.H:
            countL[j] += count_unit
            print 'count:' + str(countL[j])
        else:
            print 'count:' + str(countL[j])
    return True

In [144]:
k = df.iloc[4,:]
distri_k_to_scale(k, scale_list, count_list)
k.H

6.335

In [149]:
# update distribution on a stick at every new k
# columns = ['id','Tm','L','H','scale','count','sd']
def update_scale_distri(kDf,cur_distriL):
    L = min(cur_distriL['L'] ,kDf.L)
    H = max(cur_distriL['H'] ,kDf.H)
    if L != cur_distriL['L'] or H != cur_distri['H']:  # if HL changed: update scale
        internal = ( H - L ) / cur_distriL['sd']
        cur_distriL['scale'] = np.arange(L,H,internal)
        print 'scale list change:',kDf.Tm
        
    distri_k_to_scale(kDf,cur_distriL['scale'],cur_distriL['count'])
    
    return True

In [155]:
k = df.iloc[4,:]
update_scale_distri(k,cur_distri)
i = 4
print H,L,internal,df.H[i] - df.L[i],df.H[i] , df.L[i],tm_unit,count_unit

In [154]:
kIndex = df[(df.Tm>=Lv1A[0][0])&(df.Tm<Lv1A[1][0])].index.tolist()



    for i in kIndex[3:]:
        k = df.iloc[i,:]
        update_scale_distri(k,cur_distri)

In [161]:
df[(df.Tm>=Lv1A[1][0])&(df.Tm<Lv1A[2][0])].H.max()

6.2460000000000004

In [160]:
def calcul_distri(PiontL1,PiontL2,sd):
    
    L = df[(df.Tm>=PiontL1[0])&(df.Tm<PiontL2[0])].L.min()
    H = df[(df.Tm>=PiontL1[0])&(df.Tm<PiontL2[0])].H.max()
    internal = ( H - L ) / sd
    scale_list = np.arange(L,H,internal)
    count_list = np.zeros(sd)
    
    cur_distri = {
        'id':0,
        'Tm':PointL1[0],
        'L':L,
        'H':H,
        'scale':scale_list,
        'count':count_list,
        'sd':sd
        }
     
    kIndex = df[(df.Tm>=PiontL1[0])&(df.Tm<PiontL2[0]].index.tolist()
    for i in kIndex:
        k = df.iloc[i,:]
        distri_k_to_scale(k,cur_distri['scale'],cur_distri['count'])   
    return L,H
    
P1 = Lv1A[1]
P2 = Lv1A[2]

L,H =calcul_distri(P1,P2)
print L,' ',H