In [2]:
import pandas as pd
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

In [3]:
import pymssql
from sqlalchemy import create_engine 
engine = create_engine("mssql+pymssql://CENTALINE\zhangyun29:sh.8888@./invest")
cnx = engine.connect()

In [7]:
symbol = '002310'
starttm = '2017-11-21 20:00:00'
endtm = '2017-11-23 00:00:00'
sql_str = 'select * from M1_' + symbol + ' where time > \''+ starttm +'\'and time < \'' + endtm + '\''
df = pd.read_sql(sql_str,cnx)

In [8]:
df

                   time   open   high    low  close  volume      amount
0   2017-11-22 09:25:00  20.62  20.62  20.62  20.62   654.0   1348548.0
1   2017-11-22 09:30:00  20.67  20.78  20.67  20.73  2329.0   4829862.0
2   2017-11-22 09:31:00  20.75  20.75  20.68  20.74  2370.0   4908022.0
3   2017-11-22 09:32:00  20.72  20.74  20.70  20.70   736.0   1524366.0
4   2017-11-22 09:33:00  20.70  20.74  20.69  20.70  1436.0   2975059.0
5   2017-11-22 09:34:00  20.70  20.70  20.65  20.66  2488.0   5142215.0
6   2017-11-22 09:35:00  20.66  20.66  20.58  20.59  1631.0   3363463.0
7   2017-11-22 09:36:00  20.58  20.68  20.58  20.68  1844.0   3800656.0
8   2017-11-22 09:37:00  20.68  20.69  20.64  20.68  1311.0   2711139.0
9   2017-11-22 09:38:00  20.69  20.75  20.66  20.74  1617.0   3348011.0
10  2017-11-22 09:39:00  20.74  20.78  20.73  20.78  1638.0   3398709.0
11  2017-11-22 09:40:00  20.78  20.83  20.76  20.83  1727.0   3593482.0
12  2017-11-22 09:41:00  20.83  20.83  20.80  20.80  1320.0   2747344.0
13  2017-11-22 09:42:00  20.81  20.88  20.80  20.86  2252.0   4693940.0
14  2017-11-22 09:43:00  20.87  20.95  20.87  20.88  4176.0   8733078.0
15  2017-11-22 09:44:00  20.88  20.92  20.87  20.91  3048.0   6372352.0
16  2017-11-22 09:45:00  20.92  21.00  20.92  21.00  6538.0  13721424.0
17  2017-11-22 09:46:00  21.01  21.05  21.00  21.01  2906.0   6111851.0
18  2017-11-22 09:47:00  21.00  21.00  20.91  20.91  3366.0   7061061.0
19  2017-11-22 09:48:00  20.91  20.97  20.90  20.97  2843.0   5958522.0
20  2017-11-22 09:49:00  20.98  21.01  20.97  21.00  1507.0   3163673.0
21  2017-11-22 09:50:00  21.00  21.00  20.96  20.96  1740.0   3650507.0
22  2017-11-22 09:51:00  20.96  20.96  20.93  20.94  1002.0   2098170.0
23  2017-11-22 09:52:00  20.92  20.96  20.92  20.94  1263.0   2644174.0
24  2017-11-22 09:53:00  20.94  20.96  20.93  20.96  1160.0   2429786.0
25  2017-11-22 09:54:00  20.96  20.97  20.93  20.93  1424.0   2982468.0
26  2017-11-22 09:55:00  20.93  20.93  20.90  20.90  1356.0   2835211.0
27  2017-11-22 09:56:00  20.90  20.94  20.88  20.91  1884.0   3937340.0
28  2017-11-22 09:57:00  20.91  20.91  20.88  20.88  1013.0   2117856.0
29  2017-11-22 09:58:00  20.90  20.94  20.88  20.90  2161.0   4514450.0
..                  ...    ...    ...    ...    ...     ...         ...
211 2017-11-22 14:29:00  20.53  20.54  20.52  20.54   500.0   1026505.0
212 2017-11-22 14:30:00  20.53  20.57  20.53  20.57   741.0   1522736.0
213 2017-11-22 14:31:00  20.57  20.59  20.52  20.55  1218.0   2500348.0
214 2017-11-22 14:32:00  20.58  20.58  20.55  20.56   212.0    435939.0
215 2017-11-22 14:33:00  20.58  20.58  20.50  20.51  1396.0   2865064.0
216 2017-11-22 14:34:00  20.53  20.53  20.50  20.51   448.0    918713.0
217 2017-11-22 14:35:00  20.51  20.51  20.48  20.48   756.0   1550538.0
218 2017-11-22 14:36:00  20.48  20.50  20.45  20.45   937.0   1920959.0
219 2017-11-22 14:37:00  20.45  20.46  20.45  20.45   871.0   1781310.0
220 2017-11-22 14:38:00  20.45  20.45  20.44  20.44   677.0   1384265.0
221 2017-11-22 14:39:00  20.45  20.45  20.44  20.45   359.0    734075.0
222 2017-11-22 14:40:00  20.45  20.46  20.44  20.45   849.0   1735948.0
223 2017-11-22 14:41:00  20.46  20.46  20.40  20.40  2783.0   5684582.0
224 2017-11-22 14:42:00  20.40  20.43  20.36  20.41  3881.0   7921597.0
225 2017-11-22 14:43:00  20.41  20.44  20.41  20.44   482.0    985478.0
226 2017-11-22 14:44:00  20.44  20.45  20.43  20.45   631.0   1289676.0
227 2017-11-22 14:45:00  20.45  20.48  20.45  20.48   545.0   1115367.0
228 2017-11-22 14:46:00  20.47  20.50  20.45  20.48   978.0   2001635.0
229 2017-11-22 14:47:00  20.49  20.49  20.43  20.43   674.0   1378804.0
230 2017-11-22 14:48:00  20.44  20.44  20.40  20.42  1100.0   2246537.0
231 2017-11-22 14:49:00  20.41  20.43  20.41  20.43   739.0   1512655.0
232 2017-11-22 14:50:00  20.42  20.44  20.42  20.44   590.0   1206071.0
233 2017-11-22 14:51:00  20.44  20.48  20.43  20.46   401.0    820008.0
234 2017-11-22 14:52:00  20.46  20.50  20.45  20.47   260.0    532845.0
235 2017-11-22 14:53:00  20.47  20.47  20.45  20.46   452.0    925933.0
236 2017-11-22 14:54:00  20.45  20.46  20.43  20.43   603.0   1232594.0
237 2017-11-22 14:55:00  20.44  20.44  20.43  20.43   843.0   1726812.0
238 2017-11-22 14:56:00  20.44  20.46  20.43  20.46   395.0    808587.0
239 2017-11-22 14:57:00  20.46  20.46  20.46  20.46     3.0      6138.0
240 2017-11-22 15:00:00  20.46  20.46  20.46  20.46  1044.0   2136024.0

[241 rows x 7 columns]

In [5]:
kD = {
    'Tm',
    'O',
    'C',
    'H',
    'L',
    'Vol'
}

In [10]:
scale_list = []
count_list = []
sd = 20

In [4]:
Lv1D = {
    'Tm',
    'V',
    'D',
    'T-count',
    'change',
    'k'
}

In [18]:
Lv2D = [{
    'Tm': 1,
    'V':1,
    'D':1.0,
    'T-count':1,
    'change':0.0,
    'k':0.5
}]
tmp = {
    'Tm': 2,
    'V':2,
    'D':2.0,
    'T-count':1,
    'change':2.0,
    'k':2.5
}
Lv2D.append(tmp)
print Lv2D[1]
print Lv2D[1]['Tm']

In [13]:
Lv1_DistriD = [[]]

In [ ]:
mark = []

In [11]:
df.columns = ['Tm','O','H','L','C','V','amount']
dtCnt = len(df)

In [ ]:

stdA = [[df.O[0],df.H[0],df.L[0],df.C[0],df.Tm[0]]]
drt_std = 0

Lv1A = [[df.Tm[0],df.O[0], 0]]
cnt_up_Lv1 = 2
cnt_dn_Lv1 = 2